name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "xhck.us.kg"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.xhck.us.kg", custom_domain = true },
  { pattern = "quay.xhck.us.kg", custom_domain = true },
  { pattern = "gcr.xhck.us.kg", custom_domain = true },
  { pattern = "k8s-gcr.xhck.us.kg", custom_domain = true },
  { pattern = "k8s.xhck.us.kg", custom_domain = true },
  { pattern = "ghcr.xhck.us.kg", custom_domain = true },
  { pattern = "cloudsmith.xhck.us.kg", custom_domain = true },
]


[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
